export const sidebarLinks = [
  {
    label: 'Dashboard',
    to: '/dashboard',
    icon: 'M4 6h16M4 12h16m-7 6h7',
    requiresAuth: true,
    permission: null,
    showOnMainDomain: true,
    showOnSubdomain: false,
  },
  {
    label: 'Register',
    to: '/register',
    icon: 'M4 6h16M4 12h16m-7 6h7',
    requiresAuth: false,
    permission: null,
    showOnMainDomain: true,
    showOnSubdomain: false,
  },
  {
    label: 'Login',
    to: '/login',
    icon: 'M4 6h16M4 12h16m-7 6h7',
    requiresAuth: false,
    permission: null,
    showOnMainDomain: false,
    showOnSubdomain: true,
  },
  {
    label: 'Inventory',
    to: '/list-product',
    icon: 'M4 6h16M4 12h16m-7 6h7',
    requiresAuth: true,
    permission: 'products.index',
    showOnMainDomain: true,
    showOnSubdomain: true,
  },
  {
    label: 'POS Venta',
    to: '/pos',
    icon: 'M4 6h16M4 12h16m-7 6h7',
    requiresAuth: true,
    permission: 'sales.store',
    showOnMainDomain: true,
    showOnSubdomain: true,
  },
  {
    label: 'Roles and Permissions',
    to: '/roles-permissions',
    icon: 'M4 6h16M4 12h16m-7 6h7',
    requiresAuth: true,
    permission: 'roles.with-permissions',
    showOnMainDomain: true,
    showOnSubdomain: true,
  },
];
